# Note: Parameters can be hardcoded directly in 'deploy-functions.yaml'
# if you do not need to vary them between your functions!
description: "Function to calculate OEE"
owner: CDF Bootcamp Team
cpu: 0.5
memory: 0.2
