- name: Run calculations every 10 minutes for last hour of data
  cron: "5-59/10 * * * *"
  data:
    sites:
      - Oslo
      - Hannover
      - Nuremberg
      - Marseille
      - Houston
      - Sao Paulo
      - Kuala Lumpur
      - Chicago
      - Rotterdam
      - London
    lookback_minutes: 60
